Phase 4 ui automation
kvasiluk/python-automation pull request #6
Opened 2018-10-02 17:33 UTC by kvasiluk

2018-10-03 08:41 UTC, archick12 requested changes

2018-10-03 08:41 UTC, archick12 commented on ui_tests/test_auto_search.py
> +        if results:
Usage of IF in tests is a BAD practice, please update test.

2018-10-05 13:24 UTC, archick12 approved these changes

2018-10-05 13:24 UTC, archick12 commented on ui_tests/test_auto_login.py
> +        if fail_expected:
I would suggest to split this test to 2 tests rather than to use if in test

2018-10-05 13:24 UTC, archick12 commented on ui_tests/test_prepare_data.py
> +def test_create(create_issues):
For what this test is used for?

2018-10-05 13:24 UTC, merged

2018-10-05 13:31 UTC, kvasiluk commented on ui_tests/test_prepare_data.py
> +def test_create(create_issues):
Data preparation as a separate single call of a test, to avoid multiple API-calls in session-scope fixtures during parallel runs.